pre-commit:
  parallel: true
  commands:
    lint-filenames:
      files: git diff --cached --name-only --diff-filter=ACM
      run: node scripts/lint-filenames.js {files}
    biome:
      run: npx biome check --write
